### ISSUE TITLE
freezes on the end of the transition on iphone 6

### ISSUE THREAD

**Issue by Weedshaker** [cristianbote/phaser-state-transition#11]
Hi,

great plugin but when I tested it with phaser 2.2.2 and iphone 6 safari. tried different devices and only the iphone 6 had this issue, it froze at the end of the transition, I guess the sprite it transitions in does not hide. Anyhow, I am going to test it with phaser 2.3. Would be cool if you could have a look at this.

Greetz and thx

**Comment by cristianbote** [comment]
Just released the v2. Can you test it out?
