### ISSUE TITLE
Limit of 1 state transition per phaser project

### ISSUE THREAD

**Issue by markduiker** [cristianbote/phaser-state-transition#12]
One state transition is far better than none however I suggest allowing multiple transitions per project.

For example, I have often animated a help screen in one way and then back out in a different way, often exactly the opposite of the way it was animated in. This is to emphasize the player's return to the previous screen (back to the title or game screen). This requires two different state transitions.

Thank you for putting this project up, it is excellent!

**Comment by cristianbote** [comment]
Hi there,

Thanks for your interest! I'm really in awe with what happened with this plugin. Unfortunately, with time, comes more responsibility and it seems like, I can take this one.

Therefore, https://github.com/aaccurso/phaser-state-transition-plugin seems like the best fork that is at the moment. I would try it out. Maybe open a feature request?

In any way, thanks again, and I hope this plugin, would develop into something great, or better yet be included as core code in Phaser. Of course, tailored to fit the code base.

Have a great one!
