### ISSUE TITLE
Want to use default state parameter 

### ISSUE THREAD

**Issue by shohan4556** [cristianbote/phaser-state-transition#19]
Hello, I want to use Phaser default state parameter like this `mystate1.start(mystate2, clearWorld, clearCache, parameter)` but remember I also want to smooth transition so I have added this 
`mystate1.start('mystate2', Phaser.Plugin.StateTransition.Out.SlideBottom);`

So **How can I clear cache and pass parameter** ?

**Comment by cristianbote** [comment]
`mystate1.start('mystate2', Phaser.Plugin.StateTransition.Out.SlideBottom, null, 'foo', 'baz');`
Also, check this out: https://github.com/photonstorm/phaser/blob/v2.4.6/src/core/StateManager.js#L283
Basically, everything after the 2nd param is passed onto the new state.

**Comment by shohan4556** [comment]
great thank you.
