### ISSUE TITLE
State slide left transition in draws twice

### ISSUE THREAD

**Issue by Montoya** [cristianbote/phaser-state-transition#20]
I'm seeing this issue with the latest build: 

![transition](https://cloud.githubusercontent.com/assets/19909/13641321/006abcca-e5e6-11e5-8519-b1a9841f96d6.gif)

**Comment by cristianbote** [comment]
A fiddle or pseudocode on how exactly are you using, would help a lot. Can you please provide that?

I'm asking for this, just because there's a lot going at 'oncreate' and sliding in, is basically overlapping the upcoming state. Also, calling start twice might have same result.

Thanks!

**Comment by DWboutin** [comment]
^+1

**Comment by Montoya** [comment]
Hi @cristianbote, I've gone ahead and uploaded the whole thing here: 

http://mappdev.com/spin/

You can click on "Settings" to see the issue. 

This is the line: 

`this.state.start('SettingsScreen', Phaser.Plugin.StateTransition.Out.SlideLeft, Phaser.Plugin.StateTransition.In.SlideLeft);`

**Comment by Montoya** [comment]
Any update?

**Comment by cristianbote** [comment]
Hey @Montoya I had a few minutes and looked over your code and what it does the state navigation, and nothing stood out. The only thing that could be doing something like that, would be that the Plugin wouldn't pick the stage `backgroundColor` to fill the blank transition cover. Could you do a test and on the Settings state, at create, just set a different `backgroundColor`?

**Comment by Montoya** [comment]
OK I added `this.stage.backgroundColor = '#ff0000';` as the very line in the create method of settings screen and I'm still seeing the state drawn twice. =/

**Comment by cristianbote** [comment]
Found it! Pushing a fix into `2.0.3` soon.

**Comment by cristianbote** [comment]
Alright, should be good now. Checkout out my test sandbox https://jsfiddle.net/cristianbote/xen8usb9/2/ using the latest version.

**Comment by Montoya** [comment]
@cristianbote just wanted to let you know that I'm using the latest version and it works great, thanks!

**Comment by cristianbote** [comment]
Awesome news Christian!
