### ISSUE TITLE
Transition does not care about camera position

### ISSUE THREAD

**Issue by Owumaro** [cristianbote/phaser-state-transition#22]
I have a state where I move the camera in the `create` function. However when the transition to this state happens, it uses a snapshot taken at coordinates (0,0) regardless of the camera.

It looks like it was well done previously, but the code added for Phaser 2.4.8+ is wrong :

https://github.com/cristianbote/phaser-state-transition/blob/master/src/core/ContentSnapshot.js#L34

`this._texture.renderXY(game.world, 0, 0);`

should be replaced with

`this._texture.renderXY(game.world, -game.camera.position.x, -game.camera.position.y);`

**Comment by cristianbote** [comment]
Agh, man, indeed.
When I was migrating I knew there was something. Thanks for the heads-up! Really appreciate taking the time to flag these problems.
Update is coming.

Cheers!

**Comment by cristianbote** [comment]
Merged and publish on npm `v2.1.0`
