### ISSUE TITLE
Add list of transitions

### ISSUE THREAD

**Issue by netgfx** [cristianbote/phaser-state-transition#27]
I would like to request a list of default available transitions.

If they could include a .gif showing off the result it would benefit the user and the plugin greatly. Just a suggestion.

Thanks for this!

**Comment by cristianbote** [comment]
Hey @netgfx,

So, here's a list https://github.com/cristianbote/phaser-state-transition/blob/master/src/core/StateTransition.js#L43 for `In`, meaning sliding in also for `Out` just below it.
About that `.gif` I'm working on a fiddle for all of them. Also, I would recommend/encourage to define your own ones. That way, you'll get better control of your stuff and also getting to know the limits.

Let me know if this makes you happy.

Cheers!

**Comment by cristianbote** [comment]
Alrighty! http://codepen.io/cristianbote/pen/GjgVxg
This basically will be up-to-date, since dynamically grabs the slide options so keep an eye whenever you're in doubt.

Let me know, if this is what you had in mind.

Cheers!

**Comment by netgfx** [comment]
Yes this is perfect thanks!
