### ISSUE TITLE
Persistent Sprites Hidden behind background in Snapshot

### ISSUE THREAD

**Issue by lrojas94** [cristianbote/phaser-state-transition#30]
I'm using the stage to keep a persistent background across states, however, as I started using this plugin, the snapshot it takes moves the screen with a background (black as default since it's set to transparent in phaser). Note that after transition is done, the background stays in place.

Is there anything that can be done about this? 

For reference, I'm setting the background with game.stage.addChildAt(backgroundSprite,0);

**Comment by cristianbote** [comment]
Hey, thanks for writing this!

So, you'd like the transition to have a transparent background? I think that can be achievable. Would you like to be more explicit about what you're trying to achieve? Anything will help.

Thanks!

**Comment by lrojas94** [comment]
So, what I want to do is make it so that the transition does not remove the Stage background (Which is an animation). I've added an image at the bottom, so you can actually see what's happening. 
![haser - es6 - webpack20161024090743](https://cloud.githubusercontent.com/assets/5957926/19646934/d1565c26-99c9-11e6-960f-b59d21ffb425.gif)

As you can see, when the transition happens, a black background (or stage.background color) is added as transition is happening.

Note that the animated background is added as a **stage** child with **game.stage.addChildAt(child,0)** as previously mentioned. This is what I found out was recommended to keep sprites alive after state changes.

**Comment by cristianbote** [comment]
Hi Luis,

Nice! Thanks for the thorough explanation!

Is this gonna be some sort of modal-like experience? The thing is, between two states, everything is removed. Every child of the stage is being killed and then start the new state and go on.
What we could try is:
* Can you make the background transparent on stage?
* Adding an option to use a alpha zero fill color

I'm hopping you're using the latest version right?

I'll get back with a response if these option work as the code is right now.

Cheers!

**Comment by cristianbote** [comment]
Alrighty!
I think I got it.

So, just use the `noStage` property on your transition:

```javascript
game.state.start('mainState', {
  [...] // All other transition props
  noStage: true // Optional, of course
})
```

Please do let me know if this works.

Cheers!

**Comment by lrojas94** [comment]
It works, though it leaves a phantom image of what the future state will look like. This is a great start though :) So I believe I can take it from here.

Thanks a lot!!
:+1:

**Comment by cristianbote** [comment]
:) ah, got it.

Makes sense though. How it works is that it takes current state picture, future state picture, and leaves the future state picture on the bottom, and animates away, on top, the current state.

You can try to not animate the next state. Have you tried that before? how does it looks?
