### ISSUE TITLE
How to disable anti-aliasing during transition? 

### ISSUE THREAD

**Issue by Montoya** [cristianbote/phaser-state-transition#33]
I'm working on a game with pixel art where anti-aliasing is disabled. All of my assets are scaled 2x. They all look crisp until a state transition starts; they are blurry during the transition, and when the transition is over, they go back to being crisp again. Is there a way to ensure that the state transition plugin doesn't try to anti-alias my assets? 

Game is here: http://montoyaindustries.com/spin/

Tap the gear icon to see the title turn blurry.

**Comment by cristianbote** [comment]
Hey!

This doesn't seem to be a plugin related issue, to be honest. All it does it creates a `RenderTexture` instance from Phaser.
Looking into it, I found out that, if Phaser is not configured to not be antialiased it uses `PIXI.SCALE_MODE` as a default for textures. https://github.com/photonstorm/phaser/blob/v2.6.2/src/pixi/textures/RenderTexture.js#L90
So, your code does have `antialiasing: false` and I'm wondering what changes, and why this isn't setup as it should.

I'll get back to you once I get going with it, today.

Cheers!

**Comment by Montoya** [comment]
OK! I've also found that if I set the background to be transparent, during the transition the background is black.

**Comment by cristianbote** [comment]
Hey!

So, about the transparent background, just take a look here https://github.com/cristianbote/phaser-state-transition/issues/30#issuecomment-256034550. This was implemented a while ago.
Looking into the antialias issue.

Cheers!

**Comment by Montoya** [comment]
OK I must be doing something wrong: 
http://montoyaindustries.com/spin/

I added the noStage param to both going from menu to play and going from menu to settings, but I'm still seeing the black background. 

Code for going from menu to play: 
`this.state.start('PlayScreen', Phaser.Plugin.StateTransition.Out.ScaleUp, null, true, false, {noStage:true});` 

Code for going from menu to settings: 
`this.state.start('SettingsScreen', Phaser.Plugin.StateTransition.Out.SlideLeft, Phaser.Plugin.StateTransition.In.SlideLeft, true, false, {noStage:true});`

**Comment by Montoya** [comment]
Also I have to set clearWorld to true or else the previous state stays around as a frozen layer.

**Comment by cristianbote** [comment]
Hey!

Yeah, so `Phaser.Plugin.StateTransition.In.SlideLeft` is basically and object, on which you can pass along options. The `noStage` is a property on the transition object. I know, it's a bit unclear, as it is, I need to get some free time to do it.

Let me know of this works.
Cheers!

**Comment by Montoya** [comment]
OK, that works, and I'm also in the same boat of having the next state appear in the middle of the transition: http://montoyaindustries.com/spin/

Sounds like the only solution to that would be to have the next state start out blank and maybe tween in all the elements? Also, still have the antialiasing problem, let me know if you find a solution for that.
