### ISSUE TITLE
Blank screen before transition

### ISSUE THREAD

**Issue by nwangsg** [cristianbote/phaser-state-transition#34]
After I call transition, this happens when I have preloading in the next state:
- The screen goes blank for 500ms-2s
- The sprites of the current state re-appears
- Then the transition animation happens.

If I remove the preloading in the next state, it's working fine without any interruption.
Could you advice how to fix this?

**Comment by cristianbote** [comment]
Hey, thanks for submitting an issue!

Well, it seems that what you're describing here, might be something not supported at the moment. The plugin always calls the create method.
Feel free to submit a PR with the changes if you want, but this is not on the roadmap as we speak.

Cheers!
