### ISSUE TITLE
Feedback needed

### ISSUE THREAD

**Issue by cristianbote** [cristianbote/phaser-state-transition#35]
Hi there,

So, I'm thinking of rewriting this plugin, completely, but I need feedback, from real world users.
1. How do you use it on real games?
2. What needs to be improved?
3. What's missing?
4. Is it helpful?

I'm grateful for your answers!

Cheers!

**Comment by stephanedemotte** [comment]
A better doc :)

Need to know how we can add our custom transition, could be cool to add this in the current version ;)

**Comment by cristianbote** [comment]
Hi Stephane,

Thanks for reaching out! Is the custom transition the only thing that's left out? I'm more than happy to address it in the README.md.

Let me know if there's something else,
Cheers!

**Comment by stephanedemotte** [comment]
For the moment, yes ! It's the only thing is missing, for me ;)

I'm very new new in the game dev world. 

1 - Yes for a small game for a museum (with physical controls)
2 - I can't say a lot, i'm a noob in phaser.
3 - Like i said, a better doc
4 - Very ! Transition state, is the missing piece in PHASER.State manager 

Thanks a lot !

**Comment by cristianbote** [comment]
Thank you for all your answers, really appreciate it.
I'll get back with updates.

Thanks

**Comment by damienleroux** [comment]
Hello. Here is my feedback:

### How do you use it on real games?

I'm using PhaserJs in a React/Cordova env. I'm using [react router](https://github.com/maisano/react-router-transition) for navigation between game pages. For now, this router doesn't affect the phaser game dom element. I need to handle transitions on this dom element without react-router. I need a simple fadeIn/fadeOut transition.

### What needs to be improved? What's missing?

- The transition effect speed need to be be controlled (like [react router](https://github.com/maisano/react-router-transition) that used react-motion [spring](http://chenglou.github.io/react-motion/demos/demo5-spring-parameters-chooser/) function to handle animation stifness and damping). Maybe the props `duration` does the job. I'll test it.

- A documentation should explain how to create it own transition, what are the available props and should explain how it affects the game state.

- Maybe writing ES6 code with a babel parser to create the `dist` folder could ease the code and offer a better contribution from community.

- include a default fadeIn/fadeOut transition. If I can create one, I'll make a pull request

Is it helpful?

Yes!! Really. I  think it a very good idea to have create it. I don't know if @photonstorm think to include it in phaser 3.

Thank you!

**Comment by cristianbote** [comment]
Hey @damienleroux, thank you so much for your feedback _and_ your pull request!

I'm glad it's useful and you use it, I'll take into consideration your points, and as always, if you don't wanna wait for my free time, feel free to submit any pull request.

About the es6 conversion, I have it on my mind since, idk, 2 years ago I think. I created even a project for it, to track the progress, but free time never came around my door 😞 . I have to do it, though, it's getting really obsolete at this point.

Cheers!

**Comment by cristianbote** [comment]
Hey guys, finally managed to release a proper es6 version. Is not much, just basically what it was but in es6. I'll get to do some more improvements soon.

Thank you for your feedback, I really appreciate all the feedback and suggestions!

Cheers!
