### ISSUE TITLE
Screen blinking upon transition

### ISSUE THREAD

**Issue by ronsap123** [cristianbote/phaser-state-transition#37]
I'm building a physics based application, that doesn't have any external plugins except for admobpro. 
Do I need to terminate something in the current state before proceeding to the next to avoid the blinking?

I added an event listener that calls a function when I click on a button, the function is the following:

> game.state.start('maingame',Phaser.Plugin.StateTransition.Out.SlideRight, Phaser.Plugin.StateTransition.In.SlideRight);

Of course I have preloaded the 'maingame' state.

The screen blinks and turns black for a moment then does the transition. I've heard that other transition plugins somehow interfered with different plugins on the same project thus causing the blink, but I doubt an admob plugin will do any trouble with that..

**Comment by cristianbote** [comment]
Hey @ronsap123,

Thank you, for reaching out!

I'll try to reproduce it locally, if not on codepen or something, and come back to you. If you already have it somewhere running, please let me know to check it out.
Meanwhile, try to reduce the transition duration/speed to see if it's still visible, or if it's still blinking.

I'll get back with some results.
Cheers!

**Comment by cristianbote** [comment]
Hey @ronsap123 

Trying to clean up the issues 😄is this still relevant?

Thank you!

**Comment by ronsap123** [comment]
Hey,

Unfortunately I've dropped the project sometime after getting stuck on this
issue on a few more, had a bunch of unsynchronized libraries it was a
headache. I wasn't able to solve the issue but it was probably my poor
library handling skills. Anyways I've moved to a more native approach for
app development.
Thanks for checking but you can close the issue😊

**Comment by cristianbote** [comment]
Agh, sorry to hear that. Unfortunately that hits home 😃for me as well.

Best of luck and thanks for trying it out!
