### ISSUE TITLE
Unable to use .js

### ISSUE THREAD

**Issue by jsaade** [cristianbote/phaser-state-transition#40]
The latest .js file is giving me error when included:

```
Uncaught ReferenceError: module is not defined
    at phaser-state-transition.js:1
```

**Comment by cristianbote** [comment]
Hey @jsaade, thanks for reaching out!

Can you let me know, how do you import it?

**Comment by jsaade** [comment]
`<script src="js/phaser-state-transition.js"></script>`

Note that previous version works fine.

**Comment by cristianbote** [comment]
Yeah, that had to change, to keep up with new es6 features. Check out https://github.com/cristianbote/phaser-state-transition/blob/master/README.md#straight-but-nor-recommended

**Comment by cristianbote** [comment]
If this doesn't satisfies your need, please reopen the issue.

Thank you!
