### ISSUE TITLE
Jornhill Behavior Change?

### ISSUE THREAD

**Issue by mastastealth** [cristianbote/phaser-state-transition#6]
I know it just dropped, but might as well make it known:

It seems in 2.0.6 the behavior of the scene rendering has changed. Rather than "taking the picture" of the last scene, then doing the fade/animation, it seems to turn into a solid color instead (then fade/animate).

**Comment by cristianbote** [comment]
Is this still reproducible?

**Comment by cristianbote** [comment]
v2 released and this is not the case anymore.
