### ISSUE TITLE
not working with phaser 2.1.3 and pixi 2.0

### ISSUE THREAD

**Issue by valueerrorx** [cristianbote/phaser-state-transition#7]
it IS working in canvas mode but not with webgl.

related thread: http://www.html5gamedevs.com/topic/10015-phaser-213-and-state-transition-plugin/

**Comment by cristianbote** [comment]
Hey guys,

Love that you guys invested time in this! I'm really grateful for that. Sadly, my day-to-day job doesn't involve working with PIXI/Phaser and don't really have time for anything else.

So, wanna clear any issues that are still opened. Also, a refactoring might be in place, and coming soon.

So is this still a problem?

**Comment by imkingdavid** [comment]
The plugin seems to work for me with Phaser 2.2.2.

**Comment by cristianbote** [comment]
v2 released. It should work with the latest phaser version
