### ISSUE TITLE
Game Reversed

### ISSUE THREAD

**Issue by Moussawi7** [cristianbote/phaser-state-transition#9]
Hi,
When I use this lib. with ***Phaser v2.2.1*** it work fine but it reverse the game !!.
how I can solve this issue.
Thank you.

**Comment by ArktekniK** [comment]
I have also encountered this issue. The entire game world is upside down. 
That is, it's mirrored to be upside down, not rotated 180 degrees.

**Comment by cristianbote** [comment]
This was fixed by https://github.com/cristianbote/phaser-state-transition/pull/8
